site_name: CFDE November 2022 Meeting

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

repo_url: https://github.com/nih-cfde/2022-nov-meeting/

nav:
    - About: index.md
    - Attendees: attendees.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - COVID-19 Precautions: COVID.md
    - Restaurants: restaurants.md
    
extra:
  analytics:
    provider: custom
    property: foobar
