site_name: CFDE November 2022 Meeting

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

nav:
    - Home: index.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - COVID-19 Precautions: COVID.md